global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s

scrape_configs:
  - job_name: dzhoof-api
    metrics_path: /internal/metrics
    scheme: http
    static_configs:
      - targets: ['api:3000']
    authorization:
      credentials_file: /etc/prometheus/secrets/metrics_bearer_token
