import request from 'supertest';
import express from 'express';
import mongoose from 'mongoose';
import Reseller from '../models/Reseller';
import Plan from '../models/Plan';
import ActivationCode from '../models/ActivationCode';
import Subscription from '../models/Subscription';
import CreditTransaction from '../models/CreditTransaction';

let currentReseller: any = null;
jest.mock('../middleware/requireReseller', () => ({
  requireReseller: (req: any, _res: any, next: any) => {
    req.reseller = currentReseller;
    next();
  },
}));

// eslint-disable-next-line @typescript-eslint/no-require-imports
const resellerRouter = require('../routes/reseller');

function buildApp() {
  const app = express();
  app.use(express.json());
  app.use('/api/v1/reseller', resellerRouter);
  return app;
}

async function makePlan(name: string, durationDays: number, opts: { allowCustomDuration?: boolean } = {}) {
  return Plan.create({
    name,
    durationDays,
    maxDevices: 1,
    price: 1000,
    currency: 'DZD',
    status: 'Active',
    allowCustomDuration: opts.allowCustomDuration || false,
  });
}

async function makeReseller(username: string, planId: mongoose.Types.ObjectId, creditQty = 10) {
  const r = await Reseller.create({
    name: `محل ${username}`,
    city: 'الجزائر',
    status: 'Active',
    username,
    prefix: username.toUpperCase().slice(0, 3),
    credit: [{ planId, quantity: creditQty }],
  });
  return r.toObject();
}

// Simulate a code that was generated by the reseller and redeemed by a customer.
async function makeActivatedCode(resellerId: mongoose.Types.ObjectId, planId: mongoose.Types.ObjectId, userId: mongoose.Types.ObjectId) {
  const code = await ActivationCode.create({
    codeHash: `hash-${new mongoose.Types.ObjectId().toString()}`,
    codeLast4: '1234',
    prefix: 'TST',
    codeEnc: null,
    planId,
    status: 'ACTIVATED',
    activatedAt: new Date(),
    resellerId,
    customerName: 'زبون تجريبي',
  });
  const subscription = await Subscription.create({
    userId,
    planId,
    activationCodeId: code._id,
    status: 'ACTIVE',
    startsAt: new Date(),
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
  });
  return { code, subscription };
}

describe('Reseller code actions (إدارة الاشتراك لكل كود)', () => {
  beforeEach(async () => {
    currentReseller = null;
    await CreditTransaction.deleteMany({});
    await Subscription.deleteMany({});
    await ActivationCode.deleteMany({});
    await Reseller.deleteMany({});
    await Plan.deleteMany({});
  });

  it('renews an activated code: extends expiry, consumes credit, records ledger', async () => {
    const app = buildApp();
    const plan = await makePlan('شهري', 30);
    const reseller = await makeReseller('renewer', plan._id, 5);
    const userId = new mongoose.Types.ObjectId();
    const { code } = await makeActivatedCode(reseller._id, plan._id, userId);
    currentReseller = reseller;

    const before = new Date(Date.now() + 10 * 24 * 60 * 60 * 1000);
    await Subscription.updateOne({ activationCodeId: code._id }, { $set: { expiresAt: before } });

    const res = await request(app).post(`/api/v1/reseller/codes/${String(code._id)}/renew`).send({});
    expect(res.status).toBe(200);
    const newExpiry = new Date(res.body.data.expiresAt).getTime();
    // 10 days remaining + 30 days = ~40 days from the original expiry
    expect(newExpiry).toBeGreaterThan(before.getTime() + 29 * 24 * 60 * 60 * 1000);
    expect(res.body.data.remainingCredit).toBe(4);

    const sub = await Subscription.findOne({ activationCodeId: code._id }).lean().exec();
    expect(sub!.status).toBe('ACTIVE');
    const tx = await CreditTransaction.findOne({ type: 'CONSUME', resellerId: reseller._id }).lean().exec();
    expect(tx).not.toBeNull();
    expect(tx!.quantity).toBe(-1);
  });

  it('renews with a custom duration when the plan allows it', async () => {
    const app = buildApp();
    const plan = await makePlan('مرن', 30, { allowCustomDuration: true });
    const reseller = await makeReseller('customdur', plan._id, 5);
    const userId = new mongoose.Types.ObjectId();
    const { code } = await makeActivatedCode(reseller._id, plan._id, userId);
    currentReseller = reseller;

    const res = await request(app).post(`/api/v1/reseller/codes/${String(code._id)}/renew`).send({ customDays: 45 });
    expect(res.status).toBe(200);
    expect(res.body.data.plan.durationDays).toBe(45);
  });

  it('rejects renew when credit is insufficient and does not extend', async () => {
    const app = buildApp();
    const plan = await makePlan('شهري', 30);
    const reseller = await makeReseller('norenew', plan._id, 0);
    const userId = new mongoose.Types.ObjectId();
    const { code } = await makeActivatedCode(reseller._id, plan._id, userId);
    currentReseller = reseller;

    const res = await request(app).post(`/api/v1/reseller/codes/${String(code._id)}/renew`).send({});
    expect(res.status).toBe(400);
    expect(res.body.code).toBe('INSUFFICIENT_CREDIT');
  });

  it('changes the code plan and extends the subscription by the new plan duration', async () => {
    const app = buildApp();
    const plan30 = await makePlan('شهري', 30);
    const planYear = await makePlan('سنوي', 365);
    const reseller = await makeReseller('changer', planYear._id, 5);
    const userId = new mongoose.Types.ObjectId();
    const { code, subscription } = await makeActivatedCode(reseller._id, plan30._id, userId);
    currentReseller = reseller;

    const res = await request(app)
      .post(`/api/v1/reseller/codes/${String(code._id)}/change-plan`)
      .send({ planId: String(planYear._id) });
    expect(res.status).toBe(200);
    expect(res.body.data.plan.name).toBe('سنوي');

    const codeAfter = await ActivationCode.findById(code._id).lean().exec();
    expect(String(codeAfter!.planId)).toBe(String(planYear._id));
    const subAfter = await Subscription.findById(subscription._id).lean().exec();
    expect(String(subAfter!.planId)).toBe(String(planYear._id));
  });

  it('suspends and reactivates a subscription (playback gate uses status ACTIVE)', async () => {
    const app = buildApp();
    const plan = await makePlan('شهري', 30);
    const reseller = await makeReseller('suspender', plan._id, 5);
    const userId = new mongoose.Types.ObjectId();
    const { code } = await makeActivatedCode(reseller._id, plan._id, userId);
    currentReseller = reseller;

    const suspend = await request(app).post(`/api/v1/reseller/codes/${String(code._id)}/suspend`).send({});
    expect(suspend.status).toBe(200);
    let sub = await Subscription.findOne({ activationCodeId: code._id }).lean().exec();
    expect(sub!.status).toBe('SUSPENDED');

    // Suspending twice → 400
    const again = await request(app).post(`/api/v1/reseller/codes/${String(code._id)}/suspend`).send({});
    expect(again.status).toBe(400);

    const reactivate = await request(app).post(`/api/v1/reseller/codes/${String(code._id)}/reactivate`).send({});
    expect(reactivate.status).toBe(200);
    sub = await Subscription.findOne({ activationCodeId: code._id }).lean().exec();
    expect(sub!.status).toBe('ACTIVE');
  });

  it('enforces the permission matrix on generate / renew / change-plan / m3u', async () => {
    const app = buildApp();
    const plan = await makePlan('شهري', 30);
    const reseller = await makeReseller('restricted', plan._id, 5);
    reseller.permissions = { generateCodes: false, renew: false, changePackage: false, exportM3U: false };
    const userId = new mongoose.Types.ObjectId();
    const { code } = await makeActivatedCode(reseller._id, plan._id, userId);
    currentReseller = reseller;

    const gen = await request(app)
      .post('/api/v1/reseller/codes/generate')
      .send({ planId: String(plan._id), quantity: 1 });
    expect(gen.status).toBe(403);
    expect(gen.body.code).toBe('PERMISSION_DENIED');

    const renew = await request(app).post(`/api/v1/reseller/codes/${String(code._id)}/renew`).send({});
    expect(renew.status).toBe(403);

    const change = await request(app)
      .post(`/api/v1/reseller/codes/${String(code._id)}/change-plan`)
      .send({ planId: String(plan._id) });
    expect(change.status).toBe(403);

    const m3u = await request(app).get(`/api/v1/reseller/codes/${String(code._id)}/m3u`);
    expect(m3u.status).toBe(403);
  });

  it('exposes code detail with subscription, redemptions and devices', async () => {
    const app = buildApp();
    const plan = await makePlan('شهري', 30);
    const reseller = await makeReseller('viewer', plan._id, 5);
    const userId = new mongoose.Types.ObjectId();
    const { code } = await makeActivatedCode(reseller._id, plan._id, userId);
    currentReseller = reseller;

    const res = await request(app).get(`/api/v1/reseller/codes/${String(code._id)}`);
    expect(res.status).toBe(200);
    expect(res.body.data.subscription).toMatchObject({ status: 'ACTIVE' });
    expect(res.body.data.plan.name).toBe('شهري');
    expect(res.body.data.customerName).toBe('زبون تجريبي');
  });
});
